name: Deploy to GitHub Pages Update

on:
  push:
    branches:
      - master  # Or your main branch name, if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages (if your HTML files are in the 'public' folder)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.AVI_TOKEN }}  # Use the GitHub token for authentication
          folder: ./public  # The folder containing your static files

      # Step 3: Display GitHub Pages URL
      - name: Display GitHub Pages URL
        run: |
          echo "GitHub Pages URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}"
