name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Replace with your main branch name (it could be 'main' if that's what you're using)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages (deploy from the root directory)
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.AVI_TOKEN }}  # GitHub token for authentication
          folder: ./  # Root directory of your repository

      # Step 3: Display GitHub Pages URL
      - name: Display GitHub Pages URL
        run: |
          echo "GitHub Pages URL: https://${{ github.repository_owner }}.github.io/${{ github.repository }}"
